/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package logins;


import com.mysql.jdbc.Connection;
//import com.mysql.jdbc.Statement;
import java.sql.Statement;

import ui.LandingJPanel;
import ui.MainJFrame;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;



/**
 *
 * @author abhilashkumargorle
 */
public class AdminLoginJPanel extends javax.swing.JPanel {
    
     private MainJFrame mainframe;

    /**
     * Creates new form AdminLoginJPanel
     */
    public AdminLoginJPanel(MainJFrame mainframe) {
        
        this.mainframe =mainframe;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminLogin = new javax.swing.JPanel();
        HelloAdmin = new javax.swing.JLabel();
        adminlblUsername = new javax.swing.JLabel();
        adminlblPassword = new javax.swing.JLabel();
        adminbtnLogin = new javax.swing.JButton();
        admintxtUsername = new javax.swing.JTextField();
        adminbtnBack = new javax.swing.JButton();
        adminPassword = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(969, 407));

        AdminLogin.setBackground(new java.awt.Color(0, 102, 102));
        AdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        AdminLogin.setPreferredSize(new java.awt.Dimension(969, 407));

        HelloAdmin.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        HelloAdmin.setForeground(new java.awt.Color(255, 255, 255));
        HelloAdmin.setText("Hello, Admin!");

        adminlblUsername.setForeground(new java.awt.Color(204, 255, 255));
        adminlblUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        adminlblUsername.setText("Username :");

        adminlblPassword.setForeground(new java.awt.Color(204, 255, 255));
        adminlblPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        adminlblPassword.setText("Password :");

        adminbtnLogin.setForeground(new java.awt.Color(0, 102, 102));
        adminbtnLogin.setText("Login");
        adminbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtnLoginActionPerformed(evt);
            }
        });

        adminbtnBack.setBackground(new java.awt.Color(255, 102, 51));
        adminbtnBack.setForeground(new java.awt.Color(0, 0, 102));
        adminbtnBack.setText("Back");
        adminbtnBack.setBorder(null);
        adminbtnBack.setBorderPainted(false);
        adminbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminLoginLayout = new javax.swing.GroupLayout(AdminLogin);
        AdminLogin.setLayout(AdminLoginLayout);
        AdminLoginLayout.setHorizontalGroup(
            AdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLoginLayout.createSequentialGroup()
                .addContainerGap(396, Short.MAX_VALUE)
                .addGroup(AdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminLoginLayout.createSequentialGroup()
                        .addGroup(AdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adminlblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adminlblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(AdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(admintxtUsername)
                            .addComponent(adminPassword)))
                    .addComponent(HelloAdmin))
                .addContainerGap(411, Short.MAX_VALUE))
            .addGroup(AdminLoginLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(adminbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(431, 431, 431))
        );

        AdminLoginLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {adminPassword, adminbtnBack, adminbtnLogin});

        AdminLoginLayout.setVerticalGroup(
            AdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLoginLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(HelloAdmin)
                .addGap(43, 43, 43)
                .addGroup(AdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminlblUsername)
                    .addComponent(admintxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdminLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminlblPassword)
                    .addComponent(adminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(adminbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(adminbtnBack)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        AdminLoginLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {adminPassword, adminbtnBack});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1042, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(AdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 1036, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(AdminLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adminbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtnLoginActionPerformed
        // TODO add your handling code here:
        
        
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb?useSSL=false","root","root@1234");
            String username = admintxtUsername.getText();
            String password = adminPassword.getText();
            
            Statement stm = con.createStatement();
            String sql = "select * from login where username='"+username+"' and password='"+password+"'";
            ResultSet rs = stm.executeQuery(sql);
            
            if(rs.next())
            {
                
                AdminJPanel adminpanel = new AdminJPanel(mainframe);
                mainframe.setRightComponent(adminpanel);
            }
            else{
                
                JOptionPane.showMessageDialog(this,"username or password is incorrect");
                
                admintxtUsername.setText("");
                adminPassword.setText("");
                        
                  
                }
            
        con.close();
             
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
//        mainframe.setContentPane(adminpanel);
//        mainframe.revalidate();

         

    }//GEN-LAST:event_adminbtnLoginActionPerformed

    private void adminbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtnBackActionPerformed
          // TODO add your handling code here:
          
           LandingJPanel landingpanel = new LandingJPanel();
           mainframe.setRightComponent(landingpanel);
        
        

       
    }//GEN-LAST:event_adminbtnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminLogin;
    private javax.swing.JLabel HelloAdmin;
    private javax.swing.JPasswordField adminPassword;
    private javax.swing.JButton adminbtnBack;
    private javax.swing.JButton adminbtnLogin;
    private javax.swing.JLabel adminlblPassword;
    private javax.swing.JLabel adminlblUsername;
    private javax.swing.JTextField admintxtUsername;
    // End of variables declaration//GEN-END:variables
}
