/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package logins;

import ui.CreateEmpProfileJPanel;
import ui.LandingJPanel;
import ui.MainJFrame;

/**
 *
 * @author abhilashkumargorle
 */
public class EmployerLoginJPanel extends javax.swing.JPanel {
    
     private MainJFrame mainframe;


    /**
     * Creates new form EmployerLoginJPanel
     */
    public EmployerLoginJPanel(MainJFrame mainframe) {
        this.mainframe =mainframe;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmployerLoginJPanel2 = new javax.swing.JPanel();
        HelloProfessor4 = new javax.swing.JLabel();
        stulblUsername3 = new javax.swing.JLabel();
        stulblPassword3 = new javax.swing.JLabel();
        userbtnLogin4 = new javax.swing.JButton();
        stutxtUsername4 = new javax.swing.JTextField();
        stubtnBack3 = new javax.swing.JButton();
        stuPassword3 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        adminbtnRegister1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(969, 407));

        EmployerLoginJPanel2.setBackground(new java.awt.Color(0, 102, 102));
        EmployerLoginJPanel2.setForeground(new java.awt.Color(255, 255, 255));
        EmployerLoginJPanel2.setPreferredSize(new java.awt.Dimension(969, 407));

        HelloProfessor4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        HelloProfessor4.setForeground(new java.awt.Color(255, 255, 255));
        HelloProfessor4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HelloProfessor4.setText("Hello, Employer!");

        stulblUsername3.setForeground(new java.awt.Color(204, 255, 255));
        stulblUsername3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        stulblUsername3.setText("Username :");

        stulblPassword3.setForeground(new java.awt.Color(204, 255, 255));
        stulblPassword3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        stulblPassword3.setText("Password :");

        userbtnLogin4.setForeground(new java.awt.Color(0, 102, 102));
        userbtnLogin4.setText("Login");
        userbtnLogin4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userbtnLogin4.setBorderPainted(false);
        userbtnLogin4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userbtnLogin4ActionPerformed(evt);
            }
        });

        stubtnBack3.setBackground(new java.awt.Color(255, 102, 51));
        stubtnBack3.setForeground(new java.awt.Color(255, 255, 255));
        stubtnBack3.setText("Back");
        stubtnBack3.setBorder(null);
        stubtnBack3.setBorderPainted(false);
        stubtnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stubtnBack3ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Not registered yet? ");

        adminbtnRegister1.setBackground(new java.awt.Color(204, 255, 255));
        adminbtnRegister1.setForeground(new java.awt.Color(0, 102, 102));
        adminbtnRegister1.setText("Register");
        adminbtnRegister1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adminbtnRegister1.setBorderPainted(false);
        adminbtnRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtnRegister1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmployerLoginJPanel2Layout = new javax.swing.GroupLayout(EmployerLoginJPanel2);
        EmployerLoginJPanel2.setLayout(EmployerLoginJPanel2Layout);
        EmployerLoginJPanel2Layout.setHorizontalGroup(
            EmployerLoginJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployerLoginJPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(EmployerLoginJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HelloProfessor4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployerLoginJPanel2Layout.createSequentialGroup()
                        .addGroup(EmployerLoginJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stulblUsername3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stulblPassword3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(EmployerLoginJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stutxtUsername4)
                            .addComponent(stuPassword3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployerLoginJPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stubtnBack3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(414, 414, 414))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployerLoginJPanel2Layout.createSequentialGroup()
                .addContainerGap(439, Short.MAX_VALUE)
                .addGroup(EmployerLoginJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployerLoginJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(adminbtnRegister1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(EmployerLoginJPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(userbtnLogin4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(386, Short.MAX_VALUE))
        );
        EmployerLoginJPanel2Layout.setVerticalGroup(
            EmployerLoginJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployerLoginJPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(HelloProfessor4)
                .addGap(27, 27, 27)
                .addGroup(EmployerLoginJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stulblUsername3)
                    .addComponent(stutxtUsername4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EmployerLoginJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stulblPassword3)
                    .addComponent(stuPassword3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(userbtnLogin4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminbtnRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stubtnBack3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        EmployerLoginJPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {stuPassword3, stubtnBack3});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EmployerLoginJPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EmployerLoginJPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userbtnLogin4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userbtnLogin4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userbtnLogin4ActionPerformed

    private void stubtnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stubtnBack3ActionPerformed
        // TODO add your handling code here:
        
        LandingJPanel landingpanel = new LandingJPanel(mainframe);
           mainframe.setRightComponent(landingpanel);

       
    }//GEN-LAST:event_stubtnBack3ActionPerformed

    private void adminbtnRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtnRegister1ActionPerformed
        // TODO add your handling code here:

        CreateEmpProfileJPanel login = new CreateEmpProfileJPanel(mainframe);
        mainframe.setRightComponent(login);
    }//GEN-LAST:event_adminbtnRegister1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EmployerLoginJPanel2;
    private javax.swing.JLabel HelloProfessor4;
    private javax.swing.JButton adminbtnRegister;
    private javax.swing.JButton adminbtnRegister1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField stuPassword3;
    private javax.swing.JButton stubtnBack3;
    private javax.swing.JLabel stulblPassword3;
    private javax.swing.JLabel stulblUsername3;
    private javax.swing.JTextField stutxtUsername4;
    private javax.swing.JButton userbtnLogin4;
    // End of variables declaration//GEN-END:variables
}
