/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package logins;

import ui.LandingJPanel;
import ui.MainJFrame;

/**
 *
 * @author abhilashkumargorle
 */
public class ProfessorLoginJPanel extends javax.swing.JPanel {
    
     private MainJFrame mainframe;
    /**
     * Creates new form ProfessorLoginJPanel
     */
    public ProfessorLoginJPanel(MainJFrame mainframe) {
        
        this.mainframe =mainframe;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProfessorLoginJPanel = new javax.swing.JPanel();
        HelloProfessor = new javax.swing.JLabel();
        proflblUsername = new javax.swing.JLabel();
        proflblPassword = new javax.swing.JLabel();
        userbtnLogin = new javax.swing.JButton();
        proftxtUsername = new javax.swing.JTextField();
        profbtnBack = new javax.swing.JButton();
        profPassword = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(969, 407));

        ProfessorLoginJPanel.setBackground(new java.awt.Color(0, 102, 102));
        ProfessorLoginJPanel.setForeground(new java.awt.Color(255, 255, 255));
        ProfessorLoginJPanel.setPreferredSize(new java.awt.Dimension(969, 407));

        HelloProfessor.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        HelloProfessor.setForeground(new java.awt.Color(255, 255, 255));
        HelloProfessor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HelloProfessor.setText("Hello, Professor!");

        proflblUsername.setForeground(new java.awt.Color(204, 255, 255));
        proflblUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        proflblUsername.setText("Username :");

        proflblPassword.setForeground(new java.awt.Color(204, 255, 255));
        proflblPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        proflblPassword.setText("Password :");

        userbtnLogin.setForeground(new java.awt.Color(0, 102, 102));
        userbtnLogin.setText("Login");
        userbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userbtnLoginActionPerformed(evt);
            }
        });

        profbtnBack.setBackground(new java.awt.Color(255, 102, 51));
        profbtnBack.setForeground(new java.awt.Color(0, 0, 102));
        profbtnBack.setText("Back");
        profbtnBack.setBorder(null);
        profbtnBack.setBorderPainted(false);
        profbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profbtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProfessorLoginJPanelLayout = new javax.swing.GroupLayout(ProfessorLoginJPanel);
        ProfessorLoginJPanel.setLayout(ProfessorLoginJPanelLayout);
        ProfessorLoginJPanelLayout.setHorizontalGroup(
            ProfessorLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfessorLoginJPanelLayout.createSequentialGroup()
                .addContainerGap(338, Short.MAX_VALUE)
                .addGroup(ProfessorLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HelloProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ProfessorLoginJPanelLayout.createSequentialGroup()
                        .addGroup(ProfessorLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(proflblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(proflblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ProfessorLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(proftxtUsername)
                            .addComponent(profPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(361, Short.MAX_VALUE))
            .addGroup(ProfessorLoginJPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(ProfessorLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(profbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ProfessorLoginJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {profPassword, profbtnBack});

        ProfessorLoginJPanelLayout.setVerticalGroup(
            ProfessorLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfessorLoginJPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(HelloProfessor)
                .addGap(44, 44, 44)
                .addGroup(ProfessorLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proflblUsername)
                    .addComponent(proftxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProfessorLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proflblPassword)
                    .addComponent(profPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(userbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(profbtnBack)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        ProfessorLoginJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {profPassword, profbtnBack});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProfessorLoginJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProfessorLoginJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userbtnLoginActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_userbtnLoginActionPerformed

    private void profbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profbtnBackActionPerformed
        // TODO add your handling code here:
         LandingJPanel landingpanel = new LandingJPanel();
           mainframe.setRightComponent(landingpanel);

        
    }//GEN-LAST:event_profbtnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HelloProfessor;
    private javax.swing.JPanel ProfessorLoginJPanel;
    private javax.swing.JPasswordField profPassword;
    private javax.swing.JButton profbtnBack;
    private javax.swing.JLabel proflblPassword;
    private javax.swing.JLabel proflblUsername;
    private javax.swing.JTextField proftxtUsername;
    private javax.swing.JButton userbtnLogin;
    // End of variables declaration//GEN-END:variables
}
