/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package logins;

import ui.LandingJPanel;
import ui.MainJFrame;

/**
 *
 * @author abhilashkumargorle
 */
public class StudentLoginJPanel extends javax.swing.JPanel {
    
     private MainJFrame mainframe;

    /**
     * Creates new form StudentLoginJPanel
     */
    public StudentLoginJPanel(MainJFrame mainframe) {
         this.mainframe =mainframe;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentLoginJPanel = new javax.swing.JPanel();
        HelloProfessor1 = new javax.swing.JLabel();
        stulblUsername = new javax.swing.JLabel();
        stulblPassword = new javax.swing.JLabel();
        userbtnLogin1 = new javax.swing.JButton();
        stutxtUsername1 = new javax.swing.JTextField();
        stubtnBack = new javax.swing.JButton();
        stuPassword = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(969, 407));

        StudentLoginJPanel.setBackground(new java.awt.Color(0, 102, 102));
        StudentLoginJPanel.setForeground(new java.awt.Color(255, 255, 255));
        StudentLoginJPanel.setPreferredSize(new java.awt.Dimension(969, 407));

        HelloProfessor1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        HelloProfessor1.setForeground(new java.awt.Color(255, 255, 255));
        HelloProfessor1.setText("Hello, Student!");

        stulblUsername.setForeground(new java.awt.Color(204, 255, 255));
        stulblUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        stulblUsername.setText("Username :");

        stulblPassword.setForeground(new java.awt.Color(204, 255, 255));
        stulblPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        stulblPassword.setText("Password :");

        userbtnLogin1.setForeground(new java.awt.Color(0, 102, 102));
        userbtnLogin1.setText("Login");
        userbtnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userbtnLogin1ActionPerformed(evt);
            }
        });

        stubtnBack.setBackground(new java.awt.Color(255, 102, 51));
        stubtnBack.setForeground(new java.awt.Color(255, 255, 255));
        stubtnBack.setText("Back");
        stubtnBack.setBorder(null);
        stubtnBack.setBorderPainted(false);
        stubtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stubtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentLoginJPanelLayout = new javax.swing.GroupLayout(StudentLoginJPanel);
        StudentLoginJPanel.setLayout(StudentLoginJPanelLayout);
        StudentLoginJPanelLayout.setHorizontalGroup(
            StudentLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentLoginJPanelLayout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addGroup(StudentLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stulblUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stulblPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(StudentLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stutxtUsername1)
                    .addComponent(stuPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 355, Short.MAX_VALUE))
            .addGroup(StudentLoginJPanelLayout.createSequentialGroup()
                .addGroup(StudentLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentLoginJPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(StudentLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userbtnLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentLoginJPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(stubtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))))
                    .addGroup(StudentLoginJPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HelloProfessor1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StudentLoginJPanelLayout.setVerticalGroup(
            StudentLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentLoginJPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(HelloProfessor1)
                .addGap(42, 42, 42)
                .addGroup(StudentLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stulblUsername)
                    .addComponent(stutxtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(StudentLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stulblPassword)
                    .addComponent(stuPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(userbtnLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stubtnBack)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        StudentLoginJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {stuPassword, stubtnBack});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(StudentLoginJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(StudentLoginJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userbtnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userbtnLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userbtnLogin1ActionPerformed

    private void stubtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stubtnBackActionPerformed
        // TODO add your handling code here:
         LandingJPanel landingpanel = new LandingJPanel();
           mainframe.setRightComponent(landingpanel);

    }//GEN-LAST:event_stubtnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HelloProfessor1;
    private javax.swing.JPanel StudentLoginJPanel;
    private javax.swing.JPasswordField stuPassword;
    private javax.swing.JButton stubtnBack;
    private javax.swing.JLabel stulblPassword;
    private javax.swing.JLabel stulblUsername;
    private javax.swing.JTextField stutxtUsername1;
    private javax.swing.JButton userbtnLogin1;
    // End of variables declaration//GEN-END:variables
}
