/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package StudentWorkArea;

import ui.LandingJPanel;
import ui.MainJFrame;

/**
 *
 * @author Abhinav Uni
 */
public class StudentLandingJPanel extends javax.swing.JPanel {
    
    MainJFrame mainframe;

    /**
     * Creates new form StudentLandingJPanel
     */
    public StudentLandingJPanel(MainJFrame mainframe) {
        initComponents();
        
        this.mainframe = mainframe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFindCourses = new javax.swing.JButton();
        btnMyCourses = new javax.swing.JButton();
        btnMyProfile = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnMyTranscript = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        btnFindCourses.setForeground(new java.awt.Color(0, 102, 102));
        btnFindCourses.setText("Find Courses to Register");
        btnFindCourses.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFindCourses.setBorderPainted(false);
        btnFindCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindCoursesActionPerformed(evt);
            }
        });

        btnMyCourses.setForeground(new java.awt.Color(0, 102, 102));
        btnMyCourses.setText("My Courses");
        btnMyCourses.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMyCourses.setBorderPainted(false);
        btnMyCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyCoursesActionPerformed(evt);
            }
        });

        btnMyProfile.setForeground(new java.awt.Color(0, 102, 102));
        btnMyProfile.setText("My Profile");
        btnMyProfile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMyProfile.setBorderPainted(false);
        btnMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyProfileActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.setBorderPainted(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnMyTranscript.setForeground(new java.awt.Color(0, 102, 102));
        btnMyTranscript.setText("Transcript");
        btnMyTranscript.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMyTranscript.setBorderPainted(false);
        btnMyTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyTranscriptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMyCourses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMyTranscript, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMyCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMyTranscript, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        
        LandingJPanel landingpage = new LandingJPanel(mainframe);
        mainframe.setRightComponent(landingpage);
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnFindCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindCoursesActionPerformed
        // TODO add your handling code here:
        
        RegisterCoursesJPanel regcos = new RegisterCoursesJPanel(mainframe);
        mainframe.setRightComponent(regcos);
    }//GEN-LAST:event_btnFindCoursesActionPerformed

    private void btnMyCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyCoursesActionPerformed
        // TODO add your handling code here:
        
        myStudentCoursesJPanel courses = new myStudentCoursesJPanel(mainframe);
        mainframe.setRightComponent(courses);
        
    }//GEN-LAST:event_btnMyCoursesActionPerformed

    private void btnMyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyProfileActionPerformed
        // TODO add your handling code here:
        
        StudentViewProfileJPanel stuprofile = new StudentViewProfileJPanel(mainframe);
        mainframe.setRightComponent(stuprofile);
        
    }//GEN-LAST:event_btnMyProfileActionPerformed

    private void btnMyTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyTranscriptActionPerformed
        // TODO add your handling code here:
        
        TranscriptJPanel mytranscript = new TranscriptJPanel(mainframe);
        mainframe.setRightComponent(mytranscript);
    }//GEN-LAST:event_btnMyTranscriptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFindCourses;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMyCourses;
    private javax.swing.JButton btnMyProfile;
    private javax.swing.JButton btnMyTranscript;
    // End of variables declaration//GEN-END:variables
}
